version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: install-npm
          command: npm install
      - run: # run tests
          name: test
          command: npm run lint
            